export const seedChecklistGCG = [
  // ASPEK I. Komitmen
  { id: 1, aspek: "ASPEK I. Komitmen", deskripsi: "Pedoman Tata Kelola Perusahaan yang Baik/CoCG" },
  { id: 2, aspek: "ASPEK I. Komitmen", deskripsi: "Pedoman Perilaku/CoC" },
  { id: 3, aspek: "ASPEK I. Komitmen", deskripsi: "Penetapan Direksi sbg Penanggungjawab GCG dan SK Penunjukan Tim Komite Pemantau GCG (Bila ada)" },
  { id: 4, aspek: "ASPEK I. Komitmen", deskripsi: "Board Manual" },
  { id: 5, aspek: "ASPEK I. Komitmen", deskripsi: "Pedoman Pengendalian Gratifikasi" },
  { id: 6, aspek: "ASPEK I. Komitmen", deskripsi: "Pedoman WBS (Whistleblowing System)" },
  { id: 7, aspek: "ASPEK I. Komitmen", deskripsi: "Peraturan Disiplin Pegawai" },
  { id: 8, aspek: "ASPEK I. Komitmen", deskripsi: "PKB Terupdate" },
  { id: 9, aspek: "ASPEK I. Komitmen", deskripsi: "Dokumentasi Sosialisasi CoCG, CoC dan panduan pelaksanaan CoC kepada Organ perusahaan" },
  { id: 10, aspek: "ASPEK I. Komitmen", deskripsi: "Pernyataan Kepatuhan kepada CoC Tahun 2022 dan sebelumnya" },
  { id: 11, aspek: "ASPEK I. Komitmen", deskripsi: "Program penguatan penerapan CoC (role model, champion team)" },
  { id: 12, aspek: "ASPEK I. Komitmen", deskripsi: "Program pengenalan (orientasi) karyawan baru" },
  { id: 13, aspek: "ASPEK I. Komitmen", deskripsi: "Laporan Self Assesment GCG tahun 2023" },
  { id: 14, aspek: "ASPEK I. Komitmen", deskripsi: "TL Aol GCG" },
  { id: 15, aspek: "ASPEK I. Komitmen", deskripsi: "Annual Report Tahun 2024, Jika belum tersedia maka tahun sebelumnya (Muatan terkait Assesment/self assessment GCG)" },
  { id: 16, aspek: "ASPEK I. Komitmen", deskripsi: "Kontrak Manajemen atau KPI terkait GCG" },
  { id: 17, aspek: "ASPEK I. Komitmen", deskripsi: "Pedoman LHKPN" },
  { id: 18, aspek: "ASPEK I. Komitmen", deskripsi: "Sosialisas/Reminder penyampaian LHKPN" },
  { id: 19, aspek: "ASPEK I. Komitmen", deskripsi: "Laporan LHKPN Periodik dengan tahun pelaporan 2024" },
  { id: 20, aspek: "ASPEK I. Komitmen", deskripsi: "Sanksi terhadap Wajib Lapor yg tidak menyampaikan LHKPN" },
  { id: 21, aspek: "ASPEK I. Komitmen", deskripsi: "Pedoman Pengendalian Gratifikasi" },
  { id: 22, aspek: "ASPEK I. Komitmen", deskripsi: "Komunikasi dan Sosialisasi Gratifikasi kepada organ Perusahaan" },
  { id: 23, aspek: "ASPEK I. Komitmen", deskripsi: "Pendistribusian ketentuan Pengendalian Gratifikasi dan perangkat" },
  { id: 24, aspek: "ASPEK I. Komitmen", deskripsi: "Desiminasi Pengendalian Gratifikasi kepada Stakeholders" },
  { id: 25, aspek: "ASPEK I. Komitmen", deskripsi: "SK Unit Pengendalian Gratifikasi" },
  { id: 26, aspek: "ASPEK I. Komitmen", deskripsi: "Rencana Kerja Pengendalian Gratifikasi" },
  { id: 27, aspek: "ASPEK I. Komitmen", deskripsi: "Laporan Pelaksanaan Pengendalian Gratifikasi" },
  { id: 28, aspek: "ASPEK I. Komitmen", deskripsi: "Peninjauan dan penyempurnaan perangkat pendukung gratifikasi" },
  { id: 29, aspek: "ASPEK I. Komitmen", deskripsi: "Kebijakan WBS" },
  { id: 30, aspek: "ASPEK I. Komitmen", deskripsi: "Rencana Kerja penerapan WBS" },
  { id: 31, aspek: "ASPEK I. Komitmen", deskripsi: "Sosialisasi WBS kepada Organ perusahaan" },
  { id: 32, aspek: "ASPEK I. Komitmen", deskripsi: "Sosialisasi WBS kepada Stakeholders" },
  { id: 33, aspek: "ASPEK I. Komitmen", deskripsi: "Publikasi WBS di media lain (website, majalah)" },
  { id: 34, aspek: "ASPEK I. Komitmen", deskripsi: "Sarana/Media pendukung WBS" },
  { id: 35, aspek: "ASPEK I. Komitmen", deskripsi: "Dokumentasi Penanganan/TL atas WBS yang diterima" },
  { id: 36, aspek: "ASPEK I. Komitmen", deskripsi: "Laporan WBS (termasuk evaluasi atas pelaksanaan WBS)" },
  // ASPEK II. RUPS
  { id: 37, aspek: "ASPEK II. RUPS", deskripsi: "Pedoman pengangkatan dan pemberhentian Direksi" },
  { id: 38, aspek: "ASPEK II. RUPS", deskripsi: "SK Pengangkatan dan Pemberhentian Direksi" },
  { id: 39, aspek: "ASPEK II. RUPS", deskripsi: "CV Direksi" },
  { id: 40, aspek: "ASPEK II. RUPS", deskripsi: "Anggaran Dasar" },
  { id: 41, aspek: "ASPEK II. RUPS", deskripsi: "Pedoman pengangkatan dan pemberhentian Dekom" },
  { id: 42, aspek: "ASPEK II. RUPS", deskripsi: "SK Pengangkatan dan Pemberhentian Dekom" },
  { id: 43, aspek: "ASPEK II. RUPS", deskripsi: "Pedoman pengangkatan dan pemberhentian Dekom (proses bukan pedoman)" },
  { id: 44, aspek: "ASPEK II. RUPS", deskripsi: "SK Pengangkatan dan Pemberhentian Dekom" },
  { id: 45, aspek: "ASPEK II. RUPS", deskripsi: "CV Komisaris" },
  { id: 46, aspek: "ASPEK II. RUPS", deskripsi: "Risalah RUPS RJPP terupdate" },
  { id: 47, aspek: "ASPEK II. RUPS", deskripsi: "Dokumen Pelaksanaan RUPS RKAP Tahun 2025 (Undangan, Daftar Hadir, Paparan, Notula, Risalah, termasuk bagian yg tidak terpisahkan dari Risalah RUPS nya)" },
  { id: 48, aspek: "ASPEK II. RUPS", deskripsi: "Dokumen Pelaksanaan RUPS Risalah RUPS RKAP Tahun 2024 (Undangan, Daftar Hadir, Paparan, Notula, Risalah, termasuk bagian yg tidak terpisahkan dari Risalah RUPS nya)" },
  { id: 49, aspek: "ASPEK II. RUPS", deskripsi: "Surat Persetujuan RUPS atas aksi korporasi Perusahaan" },
  { id: 50, aspek: "ASPEK II. RUPS", deskripsi: "Dokumen Pelaksanaan RUPS Laporan Tahunan 2023 (Undangan, Daftar Hadir, Paparan, Notula, Risalah, termasuk bagian yg tidak terpisahkan dari Risalah RUPS nya)" },
  { id: 51, aspek: "ASPEK II. RUPS", deskripsi: "Surat Persetujuan RUPS atas Remunerasi Direksi dan Dekom" },
  { id: 52, aspek: "ASPEK II. RUPS", deskripsi: "Surat Penetapan auditor eksternal untuk Laporan Keuangan Tahun 2023" },
  // ASPEK III. Dewan Komisaris
  { id: 53, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Board Manual" },
  { id: 54, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Program pengenalan untuk Komisaris Baru (jika Pada Tahun 2024 terdapat pergantian)" },
  { id: 55, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Kebijakan-kebijakan (SK) yang dikeluarkan Dekom" },
  { id: 56, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Program Pengembangan Pengetahuan bagi Komisaris dan Laporan kegiatannya." },
  { id: 57, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Tanggapan Dewan Komisaris atas: Laporan Manajemen Trw I, II, III, IV 2024, RJPP, RKAP 2025 dan RKAP 2024, Laporan Tahunan 2024 (Jika belum tersedia maka digunakan tahun sebelumnya)" },
  { id: 58, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "SK Pembagian Tugas Komisaris" },
  { id: 59, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Laporan Pengawasan Dewan Komisaris Trw I, II, III, IV 2024 dan Laporan Pengawasan Dekom Tahun 2023" },
  { id: 60, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Program Kerja dan Rencana Anggaran Dekom 2024 dan 2025" },
  { id: 61, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Persetujuan Komisaris atas tindakan direksi & Pakta Integritas" },
  { id: 62, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Dokumentasi Pengusulan calon Auditor Eksternal kepada RUPS." },
  { id: 63, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Pernyataan Komisaris tidak memiliki benturan kepentingan dan hal-hal yang dapat menimbulkan benturan kepentingan" },
  { id: 64, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Tata Tertib Rapat Komisaris" },
  { id: 65, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Surat kuasa untuk anggota dekom yang tidak hadir dalam rapat" },
  { id: 66, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "SK Pengangkatan Sekretaris Komisaris" },
  { id: 67, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Uraian Tugas Sekretariat Komisaris" },
  { id: 68, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Surat-surat Dewan Komisaris Kepada Pemegang Saham" },
  { id: 69, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Surat-surat Dewan Komisaris kepada Direksi" },
  { id: 70, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Surat-surat Pemegang Saham kepada Dewan Komisaris" },
  { id: 71, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Agenda Surat Masuk dan Keluar Komisaris" },
  { id: 72, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Undangan & agenda Rapat Internal Komisaris" },
  { id: 73, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Undangan & agenda Rapat Komisaris yang Mengundang Direksi" },
  { id: 74, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Risalah Rapat Internal Komisaris" },
  { id: 75, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Risalah rapat Gabungan Komisaris" },
  { id: 76, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "SK Pengangkatan & Pemberhentian anggota Komite Audit dan Komite Komisaris Lainnya" },
  { id: 77, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Uraian Tugas Komite Audit dan Komite Komisaris lainnya" },
  { id: 78, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "CV Anggota Komite Audit dan Komite Komisaris lainnya" },
  { id: 79, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Komite Audit Charter dan Charter Komite Komisaris Lainnya" },
  { id: 80, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Program Kerja & anggaran Komite Audit dan Komite Komisaris Lainnya" },
  { id: 81, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Risalah Rapat Komite Audit dan Komite Komisaris lainnya" },
  { id: 82, aspek: "ASPEK III. Dewan Komisaris", deskripsi: "Laporan Komite Audit dan Komite Komisaris lainnya kepada Dewan Komisaris (Triwulanan dan Tahunan)" },
  // ASPEK IV. Direksi
  { id: 83, aspek: "ASPEK IV. Direksi", deskripsi: "Program Pengenalan untuk Direksi Baru" },
  { id: 84, aspek: "ASPEK IV. Direksi", deskripsi: "Program Pengembangan Pengetahuan bagi Direksi" },
  { id: 85, aspek: "ASPEK IV. Direksi", deskripsi: "SK Struktur Organisasi" },
  { id: 86, aspek: "ASPEK IV. Direksi", deskripsi: "Kajian mengenai Struktur Organisasi Perusahaan" },
  { id: 87, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Persyaratan jabatan/job specification untuk semua jabatan" },
  { id: 88, aspek: "ASPEK IV. Direksi", deskripsi: "Pedoman Penyusunan SOP" },
  { id: 89, aspek: "ASPEK IV. Direksi", deskripsi: "Daftar SOP" },
  { id: 90, aspek: "ASPEK IV. Direksi", deskripsi: "Daftar Reviu SOP" },
  { id: 91, aspek: "ASPEK IV. Direksi", deskripsi: "Mekanisme pengambilan keputusan" },
  { id: 92, aspek: "ASPEK IV. Direksi", deskripsi: "Pedoman Penyusunan RJPP" },
  { id: 93, aspek: "ASPEK IV. Direksi", deskripsi: "Draft RJPP" },
  { id: 94, aspek: "ASPEK IV. Direksi", deskripsi: "RJPP terakhir" },
  { id: 95, aspek: "ASPEK IV. Direksi", deskripsi: "Pedoman Penyusunan RKAP" },
  { id: 96, aspek: "ASPEK IV. Direksi", deskripsi: "RKAP tahun 2024 dan perubahannya, RKAP 2025" },
  { id: 97, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan SDM/Sistem Pola Karir perusahaan dan Kebijakan pengembangan SDM/Diklat" },
  { id: 98, aspek: "ASPEK IV. Direksi", deskripsi: "Data jumlah pegawai dirinci menurut unit kerja, jabatan, dan level pendidikan (pusat dan cabang)" },
  { id: 99, aspek: "ASPEK IV. Direksi", deskripsi: "Database Kompetensi" },
  { id: 100, aspek: "ASPEK IV. Direksi", deskripsi: "Daftar Urut Kepangkatan" },
  { id: 101, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Assessment Pejabat satu level (manajemen kunci) di bawah Direksi" },
  { id: 102, aspek: "ASPEK IV. Direksi", deskripsi: "Rencana promosi/suksesi (manajemen kunci)" },
  { id: 103, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan mengenai Rencana Suksesi Bagi Manajer Senior dari Direksi ke Komisaris" },
  { id: 104, aspek: "ASPEK IV. Direksi", deskripsi: "Mekanisme dalam merespon setiap usulan peluang bisnis" },
  { id: 105, aspek: "ASPEK IV. Direksi", deskripsi: "Dokumentasi usulan peluang bisnis tahun 2024" },
  { id: 106, aspek: "ASPEK IV. Direksi", deskripsi: "Surat-surat Direksi kepada Pemegang Saham" },
  { id: 107, aspek: "ASPEK IV. Direksi", deskripsi: "Surat-surat Pemegang Saham kepada Direksi" },
  { id: 108, aspek: "ASPEK IV. Direksi", deskripsi: "Surat-surat Direksi kepada Dewan Komisaris" },
  { id: 109, aspek: "ASPEK IV. Direksi", deskripsi: "Mekanisme dalam membahas isu-isu terkini tentang perubahan lingkungan bisnis" },
  { id: 110, aspek: "ASPEK IV. Direksi", deskripsi: "Mekanisme persetujuan program di luar RKAP" },
  { id: 111, aspek: "ASPEK IV. Direksi", deskripsi: "FS atas program/kegiatan yang membutuhkan investasi dan hutang" },
  { id: 112, aspek: "ASPEK IV. Direksi", deskripsi: "Pedoman Penilaian Kinerja" },
  { id: 113, aspek: "ASPEK IV. Direksi", deskripsi: "Indikator Kinerja sampai tingkat unit kerja" },
  { id: 114, aspek: "ASPEK IV. Direksi", deskripsi: "Kontrak Kinerja setiap jabatan dalam Struktur Organisasi" },
  { id: 115, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan berkala pencapaian kinerja setiap jabatan dalam Struktur Organisasi" },
  { id: 116, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Manajemen (Triwulan I, II, III dan Tahunan)" },
  { id: 117, aspek: "ASPEK IV. Direksi", deskripsi: "Uraian tugas dan tanggungjawab Direksi dan manajemen di bawahnya" },
  { id: 118, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan pelaksanaan sistem manajemen kinerja secara tertulis dari Direksi kepada Komisaris (Laporan manajemen)" },
  { id: 119, aspek: "ASPEK IV. Direksi", deskripsi: "Pengusulan insentif kinerja Direksi" },
  { id: 120, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Teknologi Informasi" },
  { id: 121, aspek: "ASPEK IV. Direksi", deskripsi: "IT Master Plan (dan Penjabarannya)" },
  { id: 122, aspek: "ASPEK IV. Direksi", deskripsi: "SK Pengelolaan TI" },
  { id: 123, aspek: "ASPEK IV. Direksi", deskripsi: "Audit atas Pengelolaan TI" },
  { id: 124, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Pelaksanaan Teknologi informasil Kepada Komisaris" },
  { id: 125, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Manajemen Mutu" },
  { id: 126, aspek: "ASPEK IV. Direksi", deskripsi: "Ketentuan/kebijakan Standar Pelayanan Minimal (SPM)" },
  { id: 127, aspek: "ASPEK IV. Direksi", deskripsi: "Pencapaian SPM" },
  { id: 128, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan keluhan pelanggan atas produk" },
  { id: 129, aspek: "ASPEK IV. Direksi", deskripsi: "Tindak lanjut atas keluhan pelanggan" },
  { id: 130, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan evaluasi sistem pengendalian mutu produk" },
  { id: 131, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan kompensasi bila mutu tidak terpenuhi" },
  { id: 132, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Pengadaan Barang dan Jasa" },
  { id: 133, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Pengadaan Barang dan Jasa" },
  { id: 134, aspek: "ASPEK IV. Direksi", deskripsi: "Rencana Pengadaan Barang dan Jasa (termasuk HPS nya)" },
  { id: 135, aspek: "ASPEK IV. Direksi", deskripsi: "SOP Pengadaan Barang dan Jasa" },
  { id: 136, aspek: "ASPEK IV. Direksi", deskripsi: "Pengumuman pengadaan Barang dan Jasa" },
  { id: 137, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan audit atas pelaksanaan barang dan jasa" },
  { id: 138, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Reward & Punishment" },
  { id: 139, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Pengembangan SDM/Diklat" },
  { id: 140, aspek: "ASPEK IV. Direksi", deskripsi: "Praktek talent pool Tahun 2024" },
  { id: 141, aspek: "ASPEK IV. Direksi", deskripsi: "Program Pendidikan dan pelatihan" },
  { id: 142, aspek: "ASPEK IV. Direksi", deskripsi: "Manual/aplikasi sistem penilaian kinerja" },
  { id: 143, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Pelaksanaan Program Pendidikan dan pelatihan" },
  { id: 144, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Evaluasi pasca pendidikan dan pelatihan" },
  { id: 145, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan/Program perlindungan keselamatan pekerja (K3)" },
  { id: 146, aspek: "ASPEK IV. Direksi", deskripsi: "Rencana program K3" },
  { id: 147, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Pelaksanaan Program K3" },
  { id: 148, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Evaluasi dan tindak lanjut program K3" },
  { id: 149, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan/SOP untuk job placement" },
  { id: 150, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan skema remunerasi karyawan dan pemenuhan hak-hak kesejahteraan karyawan (lama dan update)" },
  { id: 151, aspek: "ASPEK IV. Direksi", deskripsi: "Program reward untuk prestasi (unit dan individu)" },
  { id: 152, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Subsidiary Governance/Tata Kelola Anak Perusahaan" },
  { id: 153, aspek: "ASPEK IV. Direksi", deskripsi: "Proses Pengangkatan Direksi/Komisaris anak perusahaan" },
  { id: 154, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan/pedoman akuntansi, penyusunan LK dan management letter (lama dan update)" },
  { id: 155, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Hasil Audit atas LK, Laporan Kepatuhan, Laporan Pengendalian Intern, Laporan Kinerja Tahun 2023 dan Tahun 2024 serta LK unaudited Tahun 2024 (jika LAI Tahun 2024 belum tersedia)" },
  { id: 156, aspek: "ASPEK IV. Direksi", deskripsi: "Cascading atas asersi terhadap LK kepada tingkatan di bawah Direksi." },
  { id: 157, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Manajemen Risiko" },
  { id: 158, aspek: "ASPEK IV. Direksi", deskripsi: "Rencana Kerja penerapan Manajemen Risiko (program kerja)" },
  { id: 159, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan pelaksanaan program MR (evaluasi dan pemantauan)" },
  { id: 160, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Pelaksanaan Manajemen Risiko Kepada Komisaris" },
  { id: 161, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Sistem Pengendalian Intern" },
  { id: 162, aspek: "ASPEK IV. Direksi", deskripsi: "Asersi/pernyataan Direksi mengenai efektifitas pengendalian internal Perusahaan" },
  { id: 163, aspek: "ASPEK IV. Direksi", deskripsi: "Evaluasi atas pengendalian Internal Perusahaan" },
  { id: 164, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Pelaksanaan Tindak Lanjut atas Rekomendasi Hasil Audit dari Auditor Eksternal dan Internal yang disampaikan oleh Direksi ke Komisaris" },
  { id: 165, aspek: "ASPEK IV. Direksi", deskripsi: "Rencana Pelaksanaan Tindak Lanjut hasil audit" },
  { id: 166, aspek: "ASPEK IV. Direksi", deskripsi: "Mekanisme untuk menjaga kepatuhan perusahaan terhadap perjanjian dan komitmen perusahaan dengan pihak ketiga." },
  { id: 167, aspek: "ASPEK IV. Direksi", deskripsi: "SK tentang Fungsi/struktur menjaga kepatuhan." },
  { id: 168, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Telaahan terhadap peraturan perundang undangan yang baru" },
  { id: 169, aspek: "ASPEK IV. Direksi", deskripsi: "Kajian hukum (legal opinion) atas rencana tindakan dan permasalahan yang terjadi terkait dengan kesesuaian hukum atau ketentuan yang berlaku." },
  { id: 170, aspek: "ASPEK IV. Direksi", deskripsi: "Evaluasi kajian risiko dan legal (risk and legal review) atas rencana inisiatif bisnis, kebijakan dan rencana kerjasama yang akan dilakukan oleh perusahaan." },
  { id: 171, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan penyelesaian kasus litigasi dan non litigasi" },
  { id: 172, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan mengenai hak dan kewajiban Konsumen" },
  { id: 173, aspek: "ASPEK IV. Direksi", deskripsi: "SOP/mekanisme penanganan keluhan pelanggan" },
  { id: 174, aspek: "ASPEK IV. Direksi", deskripsi: "Program untuk mengkomunikasi produk kepada pelanggan" },
  { id: 175, aspek: "ASPEK IV. Direksi", deskripsi: "Realisasi pengkomunikasian produk kepada pelanggan" },
  { id: 176, aspek: "ASPEK IV. Direksi", deskripsi: "Rencana pelaksanaan penanganan keluhan pelanggan" },
  { id: 177, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan pelaksanaan keluhan pelanggan dan tindak lanjutnya" },
  { id: 178, aspek: "ASPEK IV. Direksi", deskripsi: "Tindak Lanjut laporan survei kepuasan pelanggan" },
  { id: 179, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan mengenai hak dan kewajiban Pemasok" },
  { id: 180, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Hasil Penilaian/Assessment Pemasok" },
  { id: 181, aspek: "ASPEK IV. Direksi", deskripsi: "Tindak lanjut rekomendasi assessment pemasok" },
  { id: 182, aspek: "ASPEK IV. Direksi", deskripsi: "Rekapitulasi pembayaran kepada tiap pemasok (memuat pembayaran seharusnya dan realisasi pembayaran)" },
  { id: 183, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan mengenai hak dan kewajiban Kreditur" },
  { id: 184, aspek: "ASPEK IV. Direksi", deskripsi: "Rekapitulasi informasi kreditur" },
  { id: 185, aspek: "ASPEK IV. Direksi", deskripsi: "Rekapitulasi pembayaran kepada bank/kreditur" },
  { id: 186, aspek: "ASPEK IV. Direksi", deskripsi: "Rekapitulasi penyampaian SPT bulanan dan tahunan" },
  { id: 187, aspek: "ASPEK IV. Direksi", deskripsi: "Rekapitulasi pembayaran pajak (pph karyawan badan PPN masa dan rampung dan PBB)" },
  { id: 188, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Hak dan Kewajiban Pegawai/Perjanjian Kerja Bersama (PKB)" },
  { id: 189, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Hasil Pengukuran Kepuasan Karyawan" },
  { id: 190, aspek: "ASPEK IV. Direksi", deskripsi: "Rencana dan tindak lanjut hasil survei kepuasan karyawan" },
  { id: 191, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan/Mekanisme baku untuk menindaklanjuti keluhan-keluhan stakeholders." },
  { id: 192, aspek: "ASPEK IV. Direksi", deskripsi: "Mekanisme penanganan keluhan stakeholder (pemasok, karyawan, dll)" },
  { id: 193, aspek: "ASPEK IV. Direksi", deskripsi: "Trend Dividen, Aset, KPI, Tk Kesehatan 3 tahun terakhir" },
  { id: 194, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan Kesehatan dan Keselamatan Kerja (K3)" },
  { id: 195, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan mengenai tanggung jawab sosial perusahaan (CSR)" },
  { id: 196, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan penanganan keluhan stakeholder" },
  { id: 197, aspek: "ASPEK IV. Direksi", deskripsi: "Unit penanggung jawab sosial, lingkungan perusahaan dan usaha kecil" },
  { id: 198, aspek: "ASPEK IV. Direksi", deskripsi: "Indikator Kinerja Pengelolaan PKBL/CSR" },
  { id: 199, aspek: "ASPEK IV. Direksi", deskripsi: "Evaluasi Pencapaian Indikator PKBL/CSR" },
  { id: 200, aspek: "ASPEK IV. Direksi", deskripsi: "Program penanganan keadaan darurat" },
  { id: 201, aspek: "ASPEK IV. Direksi", deskripsi: "Rencana Kerja CSR, PKBL" },
  { id: 202, aspek: "ASPEK IV. Direksi", deskripsi: "Pelaporan CSR, PKBL" },
  { id: 203, aspek: "ASPEK IV. Direksi", deskripsi: "Pernyataan Direksi tidak memiliki benturan kepentingan dan hal-hal yang dapat menimbulkan benturan kepentingan" },
  { id: 204, aspek: "ASPEK IV. Direksi", deskripsi: "Kebijakan mengenai benturan kepentingan" },
  { id: 205, aspek: "ASPEK IV. Direksi", deskripsi: "Pakta Integritas Direksi atas setiap usulan tindakan direksi yang perlu mendapat persetujuan Dekom dan Pemegang Saham" },
  { id: 206, aspek: "ASPEK IV. Direksi", deskripsi: "Usulan tindakan direksi yang perlu mendapat persetujuan Dekom dan PS" },
  { id: 207, aspek: "ASPEK IV. Direksi", deskripsi: "Daftar Khusus, daftar kepemilikan saham Direksi dan Dewan Komisaris beserta keluarganya di perusahaan lain" },
  { id: 208, aspek: "ASPEK IV. Direksi", deskripsi: "Surat Pengantar penyampaian Laporan Manajemen Triwulanan dan Tahunan kepada Pemegang Saham." },
  { id: 209, aspek: "ASPEK IV. Direksi", deskripsi: "Surat Pengantar penyampaian Laporan Manajemen Triwulanan dan Tahunan kepada Dewan Komisaris." },
  { id: 210, aspek: "ASPEK IV. Direksi", deskripsi: "Tata Tertib Rapat Direksi" },
  { id: 211, aspek: "ASPEK IV. Direksi", deskripsi: "Rencana Rapat Direksi" },
  { id: 212, aspek: "ASPEK IV. Direksi", deskripsi: "Undangan, Agenda & Risalah Risalah Rapat Direksi" },
  { id: 213, aspek: "ASPEK IV. Direksi", deskripsi: "SPI Charter" },
  { id: 214, aspek: "ASPEK IV. Direksi", deskripsi: "Masukan atas Draft IAC dari Dewan Komisaris (cq Komite Audit)" },
  { id: 215, aspek: "ASPEK IV. Direksi", deskripsi: "Struktur Organisasi SPI" },
  { id: 216, aspek: "ASPEK IV. Direksi", deskripsi: "SK Pengangkatan Kepala SPI" },
  { id: 217, aspek: "ASPEK IV. Direksi", deskripsi: "CV Kepala SPI & seluruh personil SPI" },
  { id: 218, aspek: "ASPEK IV. Direksi", deskripsi: "Pedoman Audit SPI" },
  { id: 219, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Pelaksanaan Tugas SPI Kepada Dirut" },
  { id: 220, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Pelatihan SDM SPI" },
  { id: 221, aspek: "ASPEK IV. Direksi", deskripsi: "Analisis beban kerja/kebutuhan tenaga SPI" },
  { id: 222, aspek: "ASPEK IV. Direksi", deskripsi: "Expedisi laporan audit SPI" },
  { id: 223, aspek: "ASPEK IV. Direksi", deskripsi: "Manual Pengawasan SPI" },
  { id: 224, aspek: "ASPEK IV. Direksi", deskripsi: "Pedoman Kendali Mutu Audit" },
  { id: 225, aspek: "ASPEK IV. Direksi", deskripsi: "Program Penjaminan Kualitas Fungsi Auditor Internal" },
  { id: 226, aspek: "ASPEK IV. Direksi", deskripsi: "Program Kerja SPI (PKPT)" },
  { id: 227, aspek: "ASPEK IV. Direksi", deskripsi: "Masukan Komite Audit atas Draft Program Kerja Audit Tahunan" },
  { id: 228, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan pencapaian Program Kerja Audit Tahunan - 2024" },
  { id: 229, aspek: "ASPEK IV. Direksi", deskripsi: "Rekomendasi SPI terhadap peningkatan proses tata kelola perusahaan" },
  { id: 230, aspek: "ASPEK IV. Direksi", deskripsi: "Rekomendasi SPI terhadap peningkatan pengelolaan risiko" },
  { id: 231, aspek: "ASPEK IV. Direksi", deskripsi: "Rekomendasi SPI terhadap pengendalian internal perusahaan" },
  { id: 232, aspek: "ASPEK IV. Direksi", deskripsi: "Evaluasi terhadap keselarasan kegiatan operasional terhadap sasaran dan tujuan organisasi dan rekomendasinya." },
  { id: 233, aspek: "ASPEK IV. Direksi", deskripsi: "Masukan yang diberikan SPI atas prosedur dan pengendalian proses-proses bisnis perusahaan." },
  { id: 234, aspek: "ASPEK IV. Direksi", deskripsi: "Masukan yang diberikan SPI tentang upaya pencapaian strategi bisnis perusahaan." },
  { id: 235, aspek: "ASPEK IV. Direksi", deskripsi: "Pedoman Pemantauan Tindak lanjut hasil audit" },
  { id: 236, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Hasil Audit SPI" },
  { id: 237, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Hasil Tindak Lanjut Hasil Audit" },
  { id: 238, aspek: "ASPEK IV. Direksi", deskripsi: "Evaluasi atas pelaksanaan tugas SPI" },
  { id: 239, aspek: "ASPEK IV. Direksi", deskripsi: "CV Sekretaris Perusahaan" },
  { id: 240, aspek: "ASPEK IV. Direksi", deskripsi: "Struktur Organisasi Sekretaris Perusahaan" },
  { id: 241, aspek: "ASPEK IV. Direksi", deskripsi: "SK Pengangkatan Sekretaris Perusahaan" },
  { id: 242, aspek: "ASPEK IV. Direksi", deskripsi: "Program Kerja Sekretaris Perusahaan" },
  { id: 243, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Kepatuhan thd Peraturan yang berlaku dan Pengendalian Intern" },
  { id: 244, aspek: "ASPEK IV. Direksi", deskripsi: "Evaluasi atas pelaksanaan tugas Sekretaris Perusahaan oleh Direksi" },
  { id: 245, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan Pelaksanaan Tugas Sekper Kepada Direksi" },
  { id: 246, aspek: "ASPEK IV. Direksi", deskripsi: "Laporan/hasil telaah tingkat kepatuhan perusahaan kepada peraturan perundang-undangan yang berlaku." },
  { id: 247, aspek: "ASPEK IV. Direksi", deskripsi: "Dokumentasi Pra RUPS RKAP" },
  { id: 248, aspek: "ASPEK IV. Direksi", deskripsi: "Dokumentasi Pra RUPS Laporan Tahunan" },
  // ASPEK V. Pengungkapan
  { id: 249, aspek: "ASPEK V. Pengungkapan", deskripsi: "Kebijakan Pengendalian informasi perusahaan/Protokol Informasi" },
  { id: 250, aspek: "ASPEK V. Pengungkapan", deskripsi: "Pelaporan Pelaksanaan KIP" },
  { id: 251, aspek: "ASPEK V. Pengungkapan", deskripsi: "Kebijakan pengelolaan website perusahaan" },
  { id: 252, aspek: "ASPEK V. Pengungkapan", deskripsi: "Majalah internal, bulletin dan tabloid perusahaan" },
  { id: 253, aspek: "ASPEK V. Pengungkapan", deskripsi: "Rencana kegiatan dengan stakeholders" },
  { id: 254, aspek: "ASPEK V. Pengungkapan", deskripsi: "Laporan Pelaksanaan kegiatan dengan stakeholders" },
  { id: 255, aspek: "ASPEK V. Pengungkapan", deskripsi: "Mekanisme Update website dan portal BUMN" },
  { id: 256, aspek: "ASPEK V. Pengungkapan", deskripsi: "Annual Report" },
  { id: 257, aspek: "ASPEK V. Pengungkapan", deskripsi: "Penghargaan di bidang CSR, bidang publikasi dan keterbukaan Informasi" },
  // ASPEK VI. Lainnya
  { id: 258, aspek: "ASPEK VI. Lainnya", deskripsi: "Penghargaan-penghargaan lainnya yang diperoleh perusahaan selama tahun 2024" },
  { id: 259, aspek: "ASPEK VI. Lainnya", deskripsi: "Dekom/Direksi/Manajemen Kunci menjadi Pembicara mewakili Perusahaan" },
  // ASPEK Tambahan - ASET
  { id: 260, aspek: "ASPEK Tambahan - ASET", deskripsi: "Kebijakan/Prosedur Manajemen Aset" },
  { id: 261, aspek: "ASPEK Tambahan - ASET", deskripsi: "Laporan Profile Asset Perusahaan (mencakup aset yang digunakan dan aset idle/tidak produktif) Tahun 2024" },
  { id: 262, aspek: "ASPEK Tambahan - ASET", deskripsi: "Rencana aksi atas aset idle/tidak produktif" },
  { id: 263, aspek: "ASPEK Tambahan - ASET", deskripsi: "Daftar aset Bantuan Pemerintah yang belum Ditetapkan statusnya (BPYBDS) sampai dengan Tahun 2024" },
  { id: 264, aspek: "ASPEK Tambahan - ASET", deskripsi: "Laporan penggunaan dana Penyertaan Modal Negara (PMN) sampai dengan Tahun 2024" },
  { id: 265, aspek: "ASPEK Tambahan - ASET", deskripsi: "Daftar investasi terhambat/terhenti/mangkrak (sampai dengan Tahun 2024, jika ada)" },
  // ASPEK Tambahan - KINERJA
  { id: 266, aspek: "ASPEK Tambahan - KINERJA", deskripsi: "Laporan Keuangan Hasil Audit Tahun 2022, 2023, 2024 (3 tahun terakhir)" },
  { id: 267, aspek: "ASPEK Tambahan - KINERJA", deskripsi: "KPI direksi perusahaan selama 5 tahun." },
  { id: 268, aspek: "ASPEK Tambahan - KINERJA", deskripsi: "Tingkat kematangan penerapan manajemen risiko selama 5 tahun (berdasarkan penilaian mandiri atau pihak eksternal) beserta Area of Improvementnya." }
]; 